armamento/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.panel_armamento, name='panel_armamento'),
    path('todo/',views.armamento, name='armamento'),
    path('activos/',views.armamento_activos, name='armamento_activos'),
    path('inactivos/',views.armamento_inactivos, name='armamento_inactivos'),
    path('movimientos/',views.movimientos_armamento, name='movimientos_armamento'),
    path('movimientos/<int:id>/',views.ver_movimiento, name='ver_movimiento'),
    path('crear_armamento/',views.crear_armamento, name='crear_armamento'),
    path('crear_armamento/excel',views.crear_armamento_excel, name='armamento_excel'),
    path('crear_armamento/excel/descargar_excel/', views.descargar_plantilla_excel, name='descargar_plantilla_excel'),
     path('ver_armamento/<int:id>/', views.ver_armamento, name='ver_armamento'),
    path('editar_armamento/<int:id>/', views.editar_armamento, name='editar_armamento'),
    path('baja_armamento/<int:id>',views.baja_armamento, name='baja_armamento'),
    path('reactivar_armamento/<int:id>',views.reactivar_armamento, name='reactivar_armamento'),
    path('eliminar_armamento/<int:id>',views.eliminar_armamento, name='eliminar_armamento'),
    path('obtener_municipios/<int:entidad_id>/', views.obtener_municipios, name='obtener_municipios'),
    path('obtener_instituciones/<int:dependencia_id>/', views.obtener_instituciones, name='obtener_instituciones'),
    ]

rnae/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogos import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from utilidades.views import error_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('catalogos/', include('catalogos.urls')),
    path('', include('sesions.urls')),
    path('armamento/', include('armamento.urls')),
    path('imagenes/', include('imagenes.urls')),
    path('error/', include('utilidades.urls')),
    path('captcha/', include('captcha.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

armamento/models.py
from django.db import models
from catalogos.models import Institucion, Dependencia, Calibre, Edo_conservacion, Entidad, Estatus_Arma, LOC, Marca, Modelo, Municipio, Tipo, TipoFuncinamiento, Propiedad
from datetime import datetime
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
import re
import unicodedata
from django.utils.translation import gettext_lazy as _
# Create your models here.

def validate_fecha_no_anterior_1990(value):
    if value < datetime(1990, 1, 1).date():
        raise ValidationError(_('La fecha no puede ser anterior al 01 de enero de 1990'))

def validate_FechaRegistro_FechaLOC(fecha_registro, fecha_loc):
    if fecha_registro < fecha_loc:
        raise ValidationError(_('La fecha de registro no puede ser menor a la Fecha de Alta del LOC'))

def validate_FechaCaptura_FechaLOC(fecha_captura, fecha_loc):
    if fecha_captura < fecha_loc:
        raise ValidationError(_('La fecha de Captura no puede ser menor a la Fecha de Alta del LOC'))    

def validate_FechaCaptura_FechaRegistro(fecha_captura, fecha_registro):
    if fecha_captura < fecha_registro:
        raise ValidationError(_('La fecha de Captura no puede ser menor a la Fecha de Registro'))

def validate_cuip_formato(value):
    if not (14 <= len(value) <= 20):
        raise ValidationError(_('El CUIP debe tener entre 14 y 20 caracteres'))

    if not value[0:4].isalpha():
        raise ValidationError(_('Los primeros 4 caracteres del CUIP deben ser letras'))

    if not value[4:10].isdigit():
        raise ValidationError(_('Los caracteres del 5 al 10 del CUIP deben ser todos dígitos'))

    if value[10] not in ['H', 'M']:
        raise ValidationError(_('El carácter en la posición 11 del CUIP debe ser H o M'))

    if not (value[11:13].isdigit() and value[11:13] in [str(i).zfill(2) for i in range(1, 33)] + ['98', '99']):
        raise ValidationError(_('Los caracteres del 12 al 13 del CUIP deben estar entre 01 y 32 o ser 98 o 99'))

    if not value[13:].isdigit():
        raise ValidationError(_('Los caracteres a partir del 14 del CUIP deben ser todos dígitos'))

def validate_AZ_09_Ñ(campo, permitir_ñ=True):
    """
    Función para validar un campo según los siguientes criterios:
    - Solo letras mayúsculas de A-Z
    - Números del 0-9
    - Opcionalmente, la letra 'Ñ' si se especifica permitir_ñ=True
    - Espacio en blanco
    """
    regex = r'^[A-Z0-9'
    if permitir_ñ:
        regex += 'Ñ'
    regex += r' ]+$'
    
    if not re.match(regex, campo):
        if permitir_ñ:
            raise ValidationError(
                'El campo solo puede contener letras mayúsculas de A-Z, la letra Ñ, números de 0-9.'
            )
        else:
            raise ValidationError(
                'El campo solo puede contener letras mayúsculas de A-Z, números de 0-9.'
            )        

def validate_especiales(campo):
    """
    Función para validar un campo que incluya letras mayúsculas de A-Z, Ñ,
    números de 0-9, y los caracteres especiales . / _ -, y espacio en blanco.
    """
    regex = r'^[A-Z0-9Ñ./_\- ]+$'
    
    if not re.match(regex, campo):
        raise ValidationError(
            _('El campo solo puede contener letras mayúsculas de A-Z, Ñ, números de 0-9, '
              'y los caracteres especiales . / _ - y espacio en blanco')
        )

def validate_09(campo):
    """
    Función para validar que un campo contenga solo números del 0 al 9.
    """
    regex = r'^[0-9]+$'
    
    if not re.match(regex, campo):
        raise ValidationError(
            'El campo solo puede contener números del 0 al 9'
        )

def validar_sin_acentos(texto):
    texto = str(texto)
    # Normalizar el texto en forma NFD (Descomposición Canónica)
    texto_normalizado = unicodedata.normalize('NFD', texto)
    
    # Comprobar si hay caracteres diacríticos (acentos) en el texto
    for char in texto_normalizado:
        if unicodedata.category(char) == 'Mn':
            raise ValidationError(_('El campo no puede contener caracteres con acentos'))

def convertir_a_mayusculas(texto):
    """
    Validator que convierte el valor a mayúsculas.
    """
    if texto is not None:
        return texto.upper()
    return texto

def save(self, *args, **kwargs):
        self.clean()
        super(Armamento, self).save(*args, **kwargs)
    
class Armamento(models.Model):
    ID_ALTERNA= models.AutoField(primary_key=True)
    ID_ARMA = models.DecimalField(max_digits=10, decimal_places=0, unique=False, null=True, blank=True)
    INSTITUCION = models.ForeignKey(Institucion, on_delete=models.RESTRICT, null=False, blank=False)
    DEPENDENCIA = models.ForeignKey(Dependencia, on_delete=models.RESTRICT, null=False, blank=False)
    ENTIDAD = models.ForeignKey(Entidad, on_delete=models.RESTRICT, null=False, blank=False)
    MUNICIPIO = models.ForeignKey(Municipio,on_delete=models.RESTRICT,to_field='id', null=False, blank=False)
    NUMERO_LOC = models.ForeignKey(LOC, on_delete=models.RESTRICT, null=False, blank=False)
    FOLIO_C = models.CharField(max_length=20, null=False, blank=False, validators=[validate_AZ_09_Ñ])
    FOLIO_D = models.CharField(max_length=20, null=False, blank=False, validators=[validate_AZ_09_Ñ])
    CLASE_TIPO_ARMA = models.ForeignKey(Tipo, on_delete=models.RESTRICT, null=False, blank=False)
    CALIBRE_ARMA = models.ForeignKey(Calibre, on_delete=models.RESTRICT, null=False, blank=False)
    MARCA_ARMA = models.ForeignKey(Marca, on_delete=models.RESTRICT, null=False, blank=False)
    MODELO_ARMA = models.ForeignKey(Modelo, on_delete=models.RESTRICT, null=False, blank=False)
    MATRICULA_CANON = models.CharField(max_length=40, null=True, blank=True, validators=[validate_AZ_09_Ñ])
    MATRICULA = models.CharField(max_length=20, null=False, blank=False, unique=True, validators=[validate_AZ_09_Ñ, validar_sin_acentos])
    MATRICULA_CANON = models.CharField(max_length=40, null=True, blank=True, validators=[validate_AZ_09_Ñ])
    FECHA = models.DateField(null=False, blank=False, validators=[validate_fecha_no_anterior_1990])
    FECHA_LOC = models.DateField(null=False, blank=False, validators=[validate_fecha_no_anterior_1990])
    ESTADO_ARMA = models.ForeignKey(Edo_conservacion, on_delete=models.RESTRICT, null=False, blank=False)
    FECHA_CAPTURA = models.DateField(null=False, blank=False, validators=[validate_fecha_no_anterior_1990])
    OBSERVACIONES = models.TextField(null=False, blank=False, validators=[validate_especiales])
    ESTATUS_ARMA = models.ForeignKey(Estatus_Arma, on_delete=models.RESTRICT, null=False, blank=False)
    CUIP_PORTADOR = models.TextField(null=False, validators=[validate_cuip_formato])
    CUIP_RESPONSABLE = models.TextField(null=False, validators=[validate_cuip_formato])
    CIHB = models.CharField(max_length=20, null=True, blank=True, validators=[validate_09])
    TIPO_FUNCIONAMIENTO = models.ForeignKey(TipoFuncinamiento, on_delete=models.RESTRICT, null=False, default=4)
    PROPIEDAD = models.ForeignKey(Propiedad, on_delete=models.RESTRICT, null=False, default=4)
    FECHA_BAJA_LOGICA = models.DateField(null=True, blank=True, validators=[validate_fecha_no_anterior_1990])
    MOTIVO_BAJA = models.TextField(null=True, blank=True)
    DOCUMENTO_BAJA = models.CharField(max_length=20, null=True, blank=True)
    OBSERVACIONES_BAJA = models.TextField(null=True, blank=True,)
    FECHA_BAJA_DOCUMENTO = models.DateField(null=True, blank=True, validators=[validate_fecha_no_anterior_1990])
    
    usuario = models.ForeignKey(User, on_delete=models.RESTRICT, null=False, blank=True)
    
    ultima_modificacion = models.DateTimeField(auto_now=True)

    def clean(self):
        # Llama al método clean() de la superclase para aplicar validaciones adicionales
        super().clean()
        self.FOLIO_C = convertir_a_mayusculas(self.FOLIO_C)
        self.FOLIO_D = convertir_a_mayusculas(self.FOLIO_D)
        self.MATRICULA = convertir_a_mayusculas(self.MATRICULA)
        self.MATRICULA_CANON = convertir_a_mayusculas(self.MATRICULA_CANON)
        self.OBSERVACIONES = convertir_a_mayusculas(self.OBSERVACIONES)
        self.CUIP_PORTADOR = convertir_a_mayusculas(self.CUIP_PORTADOR)
        self.CUIP_RESPONSABLE = convertir_a_mayusculas(self.CUIP_RESPONSABLE)
        self.OBSERVACIONES_BAJA = convertir_a_mayusculas(self.OBSERVACIONES_BAJA)
        self.MOTIVO_BAJA = convertir_a_mayusculas(self.MOTIVO_BAJA)
        self.DOCUMENTO_BAJA = convertir_a_mayusculas(self.DOCUMENTO_BAJA)

        validate_FechaRegistro_FechaLOC(self.FECHA, self.FECHA_LOC)
        validate_FechaCaptura_FechaLOC(self.FECHA_CAPTURA, self.FECHA_LOC)
        validate_FechaCaptura_FechaRegistro(self.FECHA_CAPTURA, self.FECHA)

    def __str__(self):
        return f"{self.MATRICULA}"

class ArmamentoLog(models.Model):
    id = models.AutoField(primary_key=True)
    estado = models.CharField(max_length=20)
    id_alterna= models.DecimalField(max_digits=10, decimal_places=0)
    id_arma = models.DecimalField(max_digits=10, decimal_places=0, null=True)
    institucion = models.CharField(max_length=70, null=False)
    dependencia = models.CharField(max_length=70, null=False)
    entidad = models.CharField(max_length=70, null=False)  
    municipio = models.CharField(max_length=70, null=False)
    numero_loc = models.CharField(max_length=20, null=False)
    folio_c = models.CharField(max_length=20, null=False)
    folio_d = models.CharField(max_length=20, null=False)
    clase_tipo_arma = models.CharField(max_length=50, null=False)
    calibre_arma = models.CharField(max_length=50, null=False)
    marca_arma = models.CharField(max_length=50, null=False)
    modelo_arma = models.CharField(max_length=50, null=False)
    matricula = models.CharField(max_length=20, null=False)
    matricula_canon = models.CharField(max_length=40, null=True)
    fecha = models.DateField(null=False)
    fecha_loc = models.DateField(null=False, blank=False)
    estado_arma = models.CharField(max_length=20, null=True)

armamento/templates/armamento_panel.html
{% extends "layout.html" %}
{% load i18n %}
{% load static %}
{% block favicon %}
<link rel="icon" type="image/x-icon" href="{% static 'icons/armamento.png' %}">
{% endblock %}
 {% block title %} {% trans "Panel de Armamento" %} {% endblock %} 
{% block content %}
<br>
<style>
  .background-blur {
    position: relative;
    height: 100%;
    max-width: 800px;
    margin: 0 auto;
    overflow: hidden;
  }

  .background-blur::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-image: url('/home/sistemas/RNAE/static/images/fondo_armamento.jpg');
    background-size: cover;
    background-position: center 30%;
    background-color: #929fba;
    filter: blur(4px);
    z-index: -1;
  }

  .content {
    position: relative;
    z-index: 1; /* Asegúrate de que el contenido esté por encima del pseudo-elemento */
  }
</style>
<div class="p-5 text-center bg-image rounded-3 background-blur">
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center">
      <div class="text-white d-flex align-items-center justify-content-center" style="height: 100%;">
        <h1>{% trans "Panel de Armamento" %}</h1>
    </div>
    </div>
  </div>
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-6 mb-3">
        <a href="{% url 'armamento' %}" class="btn btn-outline-light btn-lg w-100">{% trans "Todo el Armamento" %}</a>
      </div>
      <div class="col-md-6 mb-3">
        <a href="{% url 'armamento_activos' %}" class="btn btn-outline-light btn-lg w-100">{% trans " Armamento Activo" %}</a>
      </div>
      <div class="col-md-6 mb-3">
        <a href="{% url  'armamento_inactivos' %}" class="btn btn-outline-light btn-lg w-100">{%trans "Armamento Inactivo"%}</a>
      </div>
      <div class="col-md-6 mb-3">
        <a href="{% url  'movimientos_armamento' %}" class="btn btn-outline-light btn-lg w-100">{%trans "Movimientos"%}</a>
      </div>
    </div>
  </div>

  <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center">
      <div class="text-white d-flex align-items-center justify-content-center" style="height: 100%;">
        <h1>{% trans "Agregar Armamento" %}</h1>
    </div>
    </div>
  </div>
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-6 mb-3">
        <a href="{% url 'crear_armamento' %}" class="btn btn-outline-light btn-lg w-100">{% trans "Mediante Formulario" %}</a>
      </div>
      <div class="col-md-6 mb-3">
        <a href="{% url 'armamento_excel' %}" class="btn btn-outline-light btn-lg w-100">{% trans " Mediante Archivo excel" %}</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

armamento/templates/crear_armamento.html
{% extends "layout.html" %}
{% load i18n %}
{% load static %}
{% block favicon %}
<link rel="icon" type="image/x-icon" href="{% static 'icons/arma.png' %}">
{% endblock %}
 {% block title %} {% trans "Crear Armamento" %} {% endblock %} 

{% block content %}
<br><br>
<div class="card">
    <div class="card-header">
        {% trans "Crear Armamento" %}
    </div>
    <div class="card-body">
        <h4 class="card-title">{% trans "Datos del Armamento" %}</h4>
        {% include 'formArmamento.html'%}
    </div>
    <div class="card-footer text-muted">
    </div>
</div>
{% endblock %}

armamento/templates/ver_armamento.html
{% extends "layout.html" %}
{% load i18n %}
{% load static %}
{% block favicon %}
<link rel="icon" type="image/x-icon" href="{% static 'icons/arma.png' %}">
{% endblock %}
 {% block title %} {% trans "Ver Armamento" %} {% endblock %} 

{% block content %}
<br><br>
<div class="card">
    <div class="card-header">
        {% trans "Ver Armamento" %}
    </div>
    <div class="card-body">
        <h4 class="card-title">{% trans "Datos del Armamento" %}</h4>
        <form enctype="multipart/form-data" method="post" id="myForm" onsubmit="enableFieldAndSubmit(event)">
            {% csrf_token %}
        
            <div class="container">
                <div class="row">
                    <div class="col-12 col-lg-6">
                        <label for="id_ID_ARMA" class="form-label fw-bold text-muted fst-italic">{% trans "Id del Arma" %}:</label>
                        <br><input type="{{ form.ID_ARMA.field.widget.input_type }}"
                            class="form-control input-placeholder input-placeholder" 
                            name="{{ form.ID_ARMA.name }}" 
                            id="id_ID_ARMA" 
                            placeholder="{% trans 'Id del Arma' %}"
                            value="{{form.ID_ARMA.value | default:''}}" disabled><br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                        <label for="id_DEPENDENCIA" class="form-label fw-bold text-muted fst-italic">{% trans "Dependencia" %}:</label>
                        <br>{{form.DEPENDENCIA}}<br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                        <label for="id_INSTITUCION" class="form-label fw-bold text-muted fst-italic">{% trans "Institucion" %}:</label>
                        <br>{{form.INSTITUCION}}<br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                        <label for="id_ENTIDAD" class="form-label fw-bold text-muted fst-italic">{% trans "Entidad" %}:</label>
                        <br>{{form.ENTIDAD}}<br>
                    </div>
          
                    <div class="col-12 col-lg-6">
                        <label for="id_MUNICIPIO" class="form-label fw-bold text-muted fst-italic">{% trans "Municipio" %}:</label>
                        <br>{{form.MUNICIPIO}}<br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                        <label for="id_NUMERO_LOC" class="form-label fw-bold text-muted fst-italic">{% trans "Numero Loc:" %}</label>
                        <br>{{form.NUMERO_LOC}}<br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                        <label for="id_FOLIO_C" class="form-label fw-bold text-muted fst-italic">{% trans "Folio C" %}:</label>
                        <br><input type="{{ form.FOLIO_C.field.widget.input_type }}"
                            class="form-control input-placeholder input-placeholder" 
                            name="{{ form.FOLIO_C.name }}" 
                            id="id_FOLIO_C" 
                            placeholder="{% trans 'Folio C' %}"
                            value="{{form.FOLIO_C.value | default:''}}"
                            disabled><br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                        <label for="id_FOLIO_D" class="form-label fw-bold text-muted fst-italic">{% trans "Folio D" %}:</label>
                        <br><input type="{{ form.FOLIO_D.field.widget.input_type }}"
                            class="form-control input-placeholder input-placeholder" 
                            name="{{ form.FOLIO_D.name }}" 
                            id="id_FOLIO_D" 
                            placeholder="{% trans 'Folio D' %}"
                            value="{{form.FOLIO_D.value | default:''}}"
                            disabled><br>
                    </div>
        
                    <div class="col-12 col-lg-6">
                      <label for="id_CLASE_TIPO_ARMA" class="form-label fw-bold text-muted fst-italic">{% trans "Clase del Arma" %}:</label>
                        <br>{{form.CLASE_TIPO_ARMA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_CALIBRE_ARMA" class="form-label fw-bold text-muted fst-italic">{% trans "Calibre del Arma" %}:</label>
                        <br>{{form.CALIBRE_ARMA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_MARCA_ARMA" class="form-label fw-bold text-muted fst-italic">{% trans "Marca del Arma" %}:</label>
                        <br>{{form.MARCA_ARMA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_MODELO_ARMA" class="form-label fw-bold text-muted fst-italic">{% trans "Modelo del Arma" %}:</label>
                        <br>{{form.MODELO_ARMA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_matricula" class="form-label fw-bold text-muted fst-italic">{% trans "Matricula" %}:</label>
                      <br><input type="{{ form.MATRICULA.field.widget.input_type }}"
                            class="form-control input-placeholder input-placeholder" 
                            name="{{ form.MATRICULA.name }}" 
                            id="id_matricula" 
                            placeholder="{% trans 'Matricula' %}"
                            value="{{form.MATRICULA.value | default:''}}"
                            disabled
                        ><br>
                  </div>
                  
                    <div class="col-12 col-lg-6">
                      <label for="id_matricula_canon" class="form-label fw-bold text-muted fst-italic">{% trans "Matricula Canon" %}:</label>
                      <br><input type="{{ form.MATRICULA_CANON.field.widget.input_type }}"
                        class="form-control input-placeholder input-placeholder" 
                        name="{{ form.MATRICULA_CANON.name }}" 
                        id="id_matricula_canon" 
                        placeholder="{% trans 'Matricula Canon' %}"
                        value="{{form.MATRICULA_CANON.value | default:''}}"
                        disabled><br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_FECHA" class="form-label fw-bold text-muted fst-italic">{% trans "Fecha" %}:</label>
                        <br>{{form.FECHA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_FECHA_LOC" class="form-label fw-bold text-muted fst-italic">{% trans "Fecha Loc" %}:</label>
                        <br>{{form.FECHA_LOC}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_ESTADO_ARMA" class="form-label fw-bold text-muted fst-italic"> {% trans "Estado del Arma" %}:</label>
                        <br>{{form.ESTADO_ARMA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_FECHA_CAPTURA" class="form-label fw-bold text-muted fst-italic">{% trans "Fecha de Captura" %}:</label>
                        <br>{{form.FECHA_CAPTURA}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_OBSERVACIONES" class="form-label fw-bold text-muted fst-italic">{% trans "Observaciones" %}:</label>
                      <br>{{ form.OBSERVACIONES }}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_ESTATUS_ARMA" class="form-label fw-bold text-muted fst-italic">{% trans "Estatus del Arma" %}:</label>
                      <br>{{ form.ESTATUS_ARMA }}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_CUIP_PORTADOR" class="form-label fw-bold text-muted fst-italic">{% trans "CUIP Portador" %}:</label>
                      <br><input type="text"
                        class="form-control input-placeholder" 
                        name="{{ form.CUIP_PORTADOR.name }}" 
                        id="id_CUIP_PORTADOR" 
                        placeholder="{% trans 'CUIP Portador' %}"
                        value="{{form.CUIP_PORTADOR.value | default:''}}"
                        disabled><br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_CUIP_RESPONSABLE" class="form-label fw-bold text-muted fst-italic">{% trans "CUIP Responsable" %}:</label>
                      <br><input type="text"
                        class="form-control input-placeholder" 
                        name="{{ form.CUIP_RESPONSABLE.name }}" 
                        id="id_CUIP_RESPONSABLE" 
                        placeholder="{% trans 'CUIP Responsable' %}"
                        value="{{form.CUIP_RESPONSABLE.value | default:''}}"
                        disabled><br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_CIHB" class="form-label fw-bold text-muted fst-italic">{{ form.CIHB.label }}:</label>
                      <br><input type="{{ form.CIHB.field.widget.input_type }}"
                        class="form-control input-placeholder" 
                        name="{{ form.CIHB.name }}" 
                        id="id_CIHB" 
                        placeholder="{{ form.CIHB.label }}"
                        value="{{form.CIHB.value | default:''}}"
                        disabled><br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_TIPO_FUNCIONAMIENTO" class="form-label fw-bold text-muted fst-italic">{%trans "Tipo de Funcionamiento"%}:</label>
                        <br>{{form.TIPO_FUNCIONAMIENTO}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_PROPIEDAD" class="form-label fw-bold text-muted fst-italic">{%trans "Tipo de Propiedad" %}:</label>
                        <br>{{form.PROPIEDAD}}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_FECHA_BAJA_LOGICA" class="form-label fw-bold text-muted fst-italic">{% trans "Fecha de Baja Logica" %}:</label>
                      <br>{{ form.FECHA_BAJA_LOGICA }}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_MOTIVO_BAJA" class="form-label fw-bold text-muted fst-italic">{% trans "Motivo de baja" %}:</label>
                      <br>{{ form.MOTIVO_BAJA }}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_DOCUMENTO_BAJA" class="form-label fw-bold text-muted fst-italic">{% trans "Documento de Baja" %}:</label>
                      <br><input type="{{ form.DOCUMENTO_BAJA.field.widget.input_type }}"
                        class="form-control input-placeholder" 
                        name="{{ form.DOCUMENTO_BAJA.name }}" 
                        id="id_DOCUMENTO_BAJA" 
                        placeholder="{% trans 'Documento de Baja' %}"
                        value="{{form.DOCUMENTO_BAJA.value | default:''}}"
                        disabled><br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_OBSERVACIONES_BAJA" class="form-label fw-bold text-muted fst-italic">{% trans "Observaciones de Baja" %}:</label>
                      <br>{{ form.OBSERVACIONES_BAJA }}<br>
                    </div>
                
                    <div class="col-12 col-lg-6">
                      <label for="id_FECHA_BAJA_DOCUMENTO" class="form-label fw-bold text-muted fst-italic">{% trans "Fecha de baja del documento" %}:</label>
                      <br>{{ form.FECHA_BAJA_DOCUMENTO }}<br>
                    </div>
                </div>
            </div>
            {{form.ID_ALTERNA}}
            <a class="btn btn-warning mx-1" href="{% url 'editar_armamento' id %}" role="button">{% trans "Editar" %}</a>   
            <a class="btn btn-primary" href="{%url 'armamento'%}" role="button">{% trans "Volver" %}</a>
        </form>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>
{% endblock %}