imagenes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.imagenes, name='imagenes'),
    path('crear_imagen/', views.crear_imagen, name='crear_imagen'),
    path('eliminar_imagen/<int:id>', views.eliminar_imagen, name='eliminar_imagen'),
    path('editar_imagen/<int:id>', views.editar_imagen, name='editar_imagen'),
    path('obtener_instituciones/<int:dependencia_id>/', views.obtener_instituciones, name='obtener_instituciones')
]

rnae/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogos import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from utilidades.views import error_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('catalogos/', include('catalogos.urls')),
    path('', include('sesions.urls')),
    path('armamento/', include('armamento.urls')),
    path('imagenes/', include('imagenes.urls')),
    path('error/', include('utilidades.urls')),
    path('captcha/', include('captcha.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imagenes/models.py
from django.db import models
from django.forms import ValidationError
from django.core.validators import FileExtensionValidator
from catalogos.models import Institucion, Dependencia, Entidad, Tipo_Imagen
from armamento.models import Armamento
from django.contrib.auth.models import User


def validate_F_D(campo):
    # Verifica si el campo es igual a "F" o "D"
    if campo.upper() not in ['F', 'D']:
        # Si no es "F" ni "D", levanta un ValueError
        raise ValidationError("El campo debe ser 'F' o 'D'.")
    
    # Si es "F" o "D", no hace nada y retorna True opcionalmente
    return True

class Imagenes(models.Model):
    ID_ALTERNA = models.AutoField(primary_key=True)
    ID_ARMA = models.ForeignKey(Armamento, to_field='MATRICULA', on_delete=models.RESTRICT)
    IMAKEY = models.DecimalField(max_digits=10, decimal_places=0)
    DESIMA = models.CharField(max_length=80)
    FOLIO = models.DecimalField(max_digits=10, decimal_places=0)
    GRUPO = models.CharField(max_length=1, validators=[validate_F_D])
    IMAGEN = models.ImageField(upload_to='images/imagenes/',blank=False, unique=True, validators=[FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])
    DEPENDENCIA = models.ForeignKey(Dependencia, on_delete=models.RESTRICT)
    ENTIDAD = models.ForeignKey(Entidad, on_delete=models.RESTRICT)
    INSTITUCION = models.ForeignKey(Institucion, on_delete=models.RESTRICT)
    TIPO = models.ForeignKey(Tipo_Imagen, on_delete=models.RESTRICT)
    ultima_modificacion = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, on_delete=models.RESTRICT)
    
    def __str__(self):
        return f"{self.ID_ARMA} - {self.TIPO}"

class ImagenesLog(models.Model):
    imakey = models.DecimalField(max_digits=10, decimal_places=0)
    desima = models.CharField(max_length=80)
    folio = models.DecimalField(max_digits=10, decimal_places=0)
    grupo = models.CharField(max_length=1)
    imagen = models.ImageField(upload_to='respaldo/imagenes/',null=False)
    usuario = models.CharField(max_length=50)
    ultima_modificacion = models.DateTimeField()
    institucion = models.CharField(max_length=80)
    dependencia = models.CharField(max_length=80)
    entidad = models.CharField(max_length=50)
    id_alterna = models.DecimalField(max_digits=10, decimal_places=0)
    id_arma = models.CharField(max_length=20)
    tipo = models.CharField(max_length=50)
    estado = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.id_alterna} - {self.estado}  - {self.id_arma}"

imagenes/forms.py
from django import forms
from .models import  Institucion, Entidad, Dependencia, Tipo_Imagen, Armamento, Imagenes
from django.utils.translation import gettext_lazy as _

class ImagenForm(forms.ModelForm):
    class Meta:
        model = Imagenes
        fields = [
            'ID_ARMA',
            'INSTITUCION',
            'ENTIDAD',
            'DEPENDENCIA',
            'IMAKEY',
            'DESIMA',
            'TIPO',
            'FOLIO',
            'GRUPO',
            'IMAGEN'
            ]
        
    ID_ARMA = forms.ModelChoiceField(queryset=Armamento.objects.all(),to_field_name='MATRICULA',label='Matricula')
    
    INSTITUCION = forms.ModelChoiceField(queryset=Institucion.objects.all(),to_field_name='ID_INSTITUCION',label='Institucion')
    
    ENTIDAD = forms.ModelChoiceField(queryset=Entidad.objects.all(),to_field_name='ID_ENTIDAD',label='Entidad')
    
    DEPENDENCIA = forms.ModelChoiceField(queryset=Dependencia.objects.all().order_by('DEPENDENCIA'),to_field_name='ID_DEPENDENCIA',label='Dependencia')
    
    TIPO = forms.ModelChoiceField(queryset=Tipo_Imagen.objects.all().order_by('DESCRIPCION'),to_field_name='ID_IMAGEN',label='Tipo de Imagen')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ID_ARMA'].widget.attrs.update({'class': 'form-control'})
        self.fields['INSTITUCION'].widget.attrs.update({'class': 'form-control'})
        self.fields['ENTIDAD'].widget.attrs.update({'class': 'form-control'})
        self.fields['DEPENDENCIA'].widget.attrs.update({'class': 'form-control'})
        self.fields['TIPO'].widget.attrs.update({'class': 'form-control'})
        self.fields['IMAGEN'].widget.attrs.update({'class': 'form-control'})

class BusquedaImagenesForm(forms.Form):
    query = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': _('Buscar registros...')})
    )
    
    CAMPOS_BUSQUEDA = (
        ('ID_ARMA__MATRICULA__icontains', _('ID')),
        ('INSTITUCION_id__NOMBRE__icontains', _('Institucion')),
        ('ENTIDAD_id__ENTIDAD__icontains', _('Entidad')),
        ('DEPENDENCIA_id__DEPENDENCIA__icontains', _('Dependencia')),
        ('TIPO_id__DESCRIPCION__icontains', _('Tipos de Imagen'))
    )
    
    OPCIONES_ORDENADAS = sorted(CAMPOS_BUSQUEDA, key=lambda option: option[1])
    
    campos_filtrados = forms.ChoiceField(
        choices=OPCIONES_ORDENADAS,
        label=_("Filtrar por"),
        initial='ID_ARMA__MATRICULA__icontains'
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['campos_filtrados'].widget.attrs.update({
            'class': 'form-select',
            'style': 'width: 100%; max-width: 300px; font-weight: bold;'
})
        self.fields['query'].widget.attrs.update({'class': 'form-control input-placeholder', 'style': 'width: 100%; max-width: 300px;'})    

            

imagenes/views.py
import os
from django.shortcuts import get_object_or_404, render, redirect
from .models import Imagenes
from django.contrib.auth.decorators import login_required
from .forms import ImagenForm
from catalogos.models import Institucion
from django.http import JsonResponse
from .forms import BusquedaImagenesForm
from django.contrib import messages
from utilidades import utils
from django.utils.translation import gettext_lazy as _
# Create your views here.
@login_required
def imagenes(request):
    imagenes = Imagenes.objects.all().order_by('-ultima_modificacion')
    
    query = request.GET.get('query')
    valor = request.GET.get('campos_filtrados')
    
    if query and valor:
        return utils.BusquedaPersonalizada(request, query, valor, imagenes, 'imagenes.html', BusquedaImagenesForm)
        
    return utils.CrearPaginador(request, imagenes, 5, 'imagenes.html', BusquedaImagenesForm)

@login_required
def crear_imagen(request):
    if request.method == 'GET':
        form = ImagenForm(request.POST or None)
        return render(request, 'crear_imagen.html', {
            'form': form,
            'is_editing': False
        })
    else:
        form = ImagenForm(request.POST, request.FILES)
        if form.is_valid():
            objecto = form.save(commit=False)
            objecto.usuario = request.user
            objecto.save()
            messages.success(request, 'La Imagen fue agregada exitosamente.')
            return redirect('imagenes')
        else:
            return redirect('crear_imagen')

@login_required
def eliminar_imagen(request, id):
    try:
        #Obten el registro por su ID, si no existe, lanzará una excepción 404
        registro = get_object_or_404(Imagenes, pk=id)
        
        # Obtén la ruta completa de la imagen
        imagen_path = os.path.join(registro.IMAGEN.path)
        
        #Actualiza el campo usuario de quien lo elimino
        Imagenes.objects.filter(pk=id).update(usuario=request.user)
        
        # Borra el registro y luego la imagen
        registro.delete()
        os.remove(imagen_path)
        
    except Exception as e:
        # Si ocurre una excepción, maneja el error apropiadamente
        messages.error(request, f'Error al eliminar: {e}')

    messages.success(request, 'La Imagen fue eliminada exitosamente.')    
    return redirect('imagenes')  # Redirige a la misma vista

@login_required
def editar_imagen(request, id):
        imagen = get_object_or_404(Imagenes,pk=id)
        ruta = f"/home/sistemas/RNAE{imagen.IMAGEN.url}"
        
        form = ImagenForm(request.POST or None, request.FILES or None, instance=imagen)

        if form.is_valid() and request.method == 'POST':
            if 'IMAGEN' in form.changed_data:
                utils.EliminarImagenAntigua(ruta)
            objeto = form.save(commit=False)
            objeto.usuario = request.user     
            objeto.save()
            messages.success(request, 'La Imagen fue editada exitosamente.')
            return redirect('imagenes')
        return render(request, 'editar_imagen.html', {
            'form': form,
            'is_editing': True
            })
        
@login_required
def obtener_instituciones(dependencia_id):
    try:
        instituciones = Institucion.objects.filter(ID_DEPENDENCIA=dependencia_id).values('ID_INSTITUCION', 'NOMBRE')

        return JsonResponse(list(instituciones), safe=False)

    except Institucion.DoesNotExist:
        # Manejo de error si no se encuentra o no existen instituciones asociadas
        return JsonResponse([], safe=False)
    
    

imagenes/templates/crear_imagen.html
{% extends "layout.html" %}
{% load i18n %}
{% load static %}
{% block favicon %}
<link rel="icon" type="image/x-icon" href="{% static 'icons/foto_unica.png' %}">
{% endblock %}
 {% block title %} {% trans "Crear Imagen" %} {% endblock %} 

{% block content %}
<br><br>
<div class="card">
    <div class="card-header">
        {% trans "Crear Imagen" %}
    </div>
    <div class="card-body">
        <h4 class="card-title">{% trans "Datos de la Imagen"%}</h4>
        <div class="container">
            {% include 'formImagen.html'%}
        </div>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}

imagenes/templates/editar_imagen.html
{% extends "layout.html" %}
{% load i18n %}
{% load static %}
{% block favicon %}
<link rel="icon" type="image/x-icon" href="{% static 'icons/foto_unica.png' %}">
{% endblock %}
 {% block title %} {% trans "Editar Imagen"%} {% endblock %} 

{% block content %}
<br><br>
<div class="card">
    <div class="card-header">
        {% trans "Editar Imagen"%}
    </div>
    <div class="card-body">
        <h4 class="card-title">{% trans "Datos de la Imagen"%}</h4>
        <div class="container">
            {% include 'formImagen.html'%}
        </div>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}

imagenes/templates/formImagen.html
{% load i18n %}
{% load static %}

<form enctype="multipart/form-data" method="post" id="myForm" onsubmit="enableFieldAndSubmit(event)">
  {% csrf_token %}
<br>
  <div class="mb-3 row">
    <div class="col-md-6 col-sm-12">
      <label for="{{ form.ID_ARMA.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{% trans "Matricula del Arma existente" %}:</label>
      {{ form.ID_ARMA }}
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-md-6 col-sm-12">
        <label for="{{ form.DEPENDENCIA.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{% trans "Dependencia"%}:</label>
        {{ form.DEPENDENCIA }}
    </div>

    <div class="col-md-6 col-sm-12">
      <label for="{{ form.INSTITUCION.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{% trans "Institución" %}:</label>
      {{ form.INSTITUCION }}
    </div>
  </div>

  <div class="mb-3 row">

    <div class="col-md-6 col-sm-12">
      <label for="{{ form.ENTIDAD.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{% trans "Entidad Federativa" %}:</label>
      <div>{{ form.ENTIDAD }}</div>
    </div>

    <div class="col-md-6 col-sm-12">
      <label for="{{ form.IMAKEY.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{{ form.IMAKEY.label|title }}:</label>
      <input type="number" 
              class="form-control input-placeholder input-placeholder" 
              name="{{ form.IMAKEY.name }}" 
              placeholder="{{ form.IMAKEY.label|title }}" 
              value="{{ form.IMAKEY.value | default:'' }}" 
              id="id_IMAKEY" required>
        {% if form.IMAKEY.errors %}
        <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
          {% for error in form.IMAKEY.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div>{% endif %}
    </div>

  </div>

  <div class="mb-3 row">

    <div class="col-md-6 col-sm-12">
      <label for="{{ form.DESIMA.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{{ form.DESIMA.label|title }}:</label>
      <input type="{{ form.DESIMA.field.widget.input_type }}" 
             class="form-control input-placeholder" 
             name="{{ form.DESIMA.name }}" 
             placeholder="{{ form.DESIMA.label|title }}" 
             value="{{ form.DESIMA.value | default:'' }}" 
             id="id_DESIMA" required>
      {% if form.IMAKEY.errors %}
        <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
          {% for error in form.IMAKEY.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div> {% endif %}
    </div>

    <div class="col-md-6 col-sm-12">
      <label for="{{ form.TIPO.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{% trans "Tipo de Imagen" %}:</label>
      {{ form.TIPO }}
    </div>

  </div>

  <div class="mb-3 row">

    <div class="col-md-6 col-sm-12">
      <label for="{{ form.FOLIO.id_for_label }}" class="form-label fw-bold text-muted fst-italic">{{ form.FOLIO.label|title }}:</label>
      <input type="{{ form.FOLIO.field.widget.input_type }}" 
             class="form-control input-placeholder" 
             name="{{ form.FOLIO.name }}" 
             placeholder="{{ form.FOLIO.label|title }}" 
             value="{{ form.FOLIO.value | default:'' }}" 
             id="id_FOLIO" 
             required>
    </div>
    
    <div class="col-md-6 col-sm-12">
      <label for="" class="form-label fw-bold text-muted fst-italic">{% trans "Grupo" %}:</label>
      <input type="{{ form.GRUPO.field.widget.input_type }}"
             oninput="this.value = this.value.toUpperCase();" 
             class="form-control input-placeholder" 
             name="{{ form.GRUPO.name }}" 
             placeholder="{{ form.GRUPO.label|title }}" 
             value="{{ form.GRUPO.value | default:'' }}" 
             maxlength="1" id="id_GRUPO" 
             required>
             {% if form.GRUPO.errors %}
        <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
          {% for error in form.GRUPO.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div>{% endif %}
    </div>
    
  </div>

<div class="mb-3 row">
  <div class="col-md-6 col-sm-12">
    <label for="id_IMAGEN" class="form-label fw-bold text-muted fst-italic">{% trans "Imagen del Arma" %}:</label><br>
    {% if form.IMAGEN.value %}
    <img src="{{ form.IMAGEN.value.url }}" width="300"><br>
    {% endif %}
    {{ form.IMAGEN }}
  </div>
</div>

  <input class="btn btn-success" type="submit" value="{% trans 'Guardar' %}"" id="guardar-btn">
  <a class="btn btn-primary" href="{% url 'imagenes' %}" role="button">{% trans "Volver" %}</a>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/instituciones.js' %}"></script>
<script src="{% static 'js/tecla_enter.js' %}"></script>
{% if is_editing %}
<script src="{% static 'js/boton_guardar.js' %}"></script>
  <script src="{% static 'js/deshabilitar_idArma.js' %}"></script>
{% endif %}

imagenes/templates/imagenes.html
{% extends "layout.html" %}
{% load i18n %}
{% load static %}
{% block favicon %}
<link rel="icon" type="image/x-icon" href="{% static 'icons/fotos_varias.png' %}">
{% endblock %}
 {% block title %} {% trans "Imagenes" %} {% endblock %} 

{% block content %}
<br><br>
{% if messages %}
<div>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
</div>
{% endif %}
<div class="card">
    <div class="card-header">
        <h1 style="text-align:center;">{% trans "IMÁGENES" %}</h1>
        <div class="d-flex justify-content-between flex-wrap">
          <a class="btn btn-success d-flex align-items-center" href="{% url 'crear_imagen' %}" role="button">
              {% trans "Agregar nueva imagen" %}
          </a>
      
          <div class="mb-2 mb-md-0">
              <form method="GET" action="" onsubmit="return validarForm()">
                <div class="col-auto d-flex align-items-center">
                  <div class="p-1">
                      {{ form.campos_filtrados.label_tag }}
                  </div>
                  <div class="p-1">
                      {{ form.campos_filtrados }}
                  </div>
                  <div class="p-1">
                      {{ form.query }}
                  </div>
                  <div class="p-1">
                      <button type="submit" class="btn btn-outline-secondary">
                          <i class="fa fa-search"></i>
                      </button>
                  </div>
                  <div class="p-1">
                      <a class="btn btn-danger" href="{% url 'imagenes' %}" role="button">
                          <i class="fa fa-refresh" aria-hidden="true"></i>
                      </a>
                  </div>
              </div>
              </form>
          </div>
      </div>
      
    </div>
    <div class="d-flex justify-content-end me-3 me-3">
      <span class="fw-light fst-italic">{% trans "Total de registros" %}: {{ num_registros }}</span>
  </div>
    <div class="card-body table-responsive">
        <table class="table table table-striped table-bordered">
            <thead>
              <tr class="text-center align-middle">
                <th scope="col">{% trans "ID ARMA" %}</th>
                <th scope="col">{% trans "IMAGEN" %}</th>
                <th scope="col">{% trans "DEPENDENCIA" %}</th>
                <th scope="col">{% trans "INSTITUCIÓN" %}</th>
                <th scope="col">{% trans "ENTIDAD" %}</th>
                <th scope="col">{% trans "IMAKEY" %}</th>
                <th scope="col">{% trans "DESIMA" %}</th>
                <th scope="col">{% trans "TIPO" %}</th>
                <th scope="col">{% trans "FOLIO" %}</th>
                <th scope="col">{% trans "GRUPO" %}</th>
                <th scope="col">{% trans "ACCIONES" %}</th>
              </tr>
            </thead>
            <tbody>
              {% for imagen in lista %}
              <tr class="text-center align-middle">
                <td>{{ imagen.ID_ARMA }}</td>
                <td><img src="{{ imagen.IMAGEN.url }}" height="100" /></td>
                <td>{{ imagen.DEPENDENCIA }}</td>
                <td>{{ imagen.INSTITUCION }}</td>
                <td>{{ imagen.ENTIDAD }}</td>
                <td>{{ imagen.IMAKEY }}</td>
                <td>{{ imagen.DESIMA }}</td>
                <td>{{ imagen.TIPO }}</td>
                <td>{{ imagen.FOLIO }}</td>
                <td>{{ imagen.GRUPO }}</td>
                <td class="w-100 h-100">
                  <div class="d-flex justify-content-center align-items-center">
                    <a name="" id="" class="btn btn-warning  mx-1" href="{% url 'editar_imagen' imagen.ID_ALTERNA %}" role="button">{% trans "Editar" %}</a>
                    <button data-url="{% url 'eliminar_imagen' imagen.ID_ALTERNA %}" class="boton-borrar btn btn-danger  mx-1">{% trans "Eliminar" %}</button>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
    <div class="container mt-4">
      {% if mensaje %}
          <!-- Muestra el mensaje de Bootstrap si está presente -->
          <div class="alert alert-info" role="alert">
              {{ mensaje }}
          </div>
      {% endif %}
</div>
<div class="card-footer text-muted">
</div>
</div>
<br>
<div class="pagination">
  {% include 'paginador.html' %}
</div>
<script src="{% static 'js/confirmar_eliminacion.js' %}"></script>
<script src="{% static 'js/validar_formulario.js' %}"></script>
{% endblock %}